language: node_js
node_js:
  - 13

services:
  - docker

env:
  - DOCKER_PASSWORD=abraham2@
  - DOCKER_USERNAME=zenithcoder

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed zenithcoder/udagram-api-feed:latest
  - docker tag udagram-api-user zenithcoder/udagram-api-user:latest
  - docker tag udagram-reverseproxy zenithcoder/udagram-reverseproxy:latest
  - docker tag udagram-frontend zenithcoder/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zenithcoder/udagram-api-feed
  - docker push zenithcoder/udagram-api-user
  - docker push zenithcoder/udagram-reverseproxy
  - docker push zenithcoder/udagram-frontend